apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: notes-tls
spec:
  secretName: notes-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: notes.justinlucedev.com
  dnsNames:
  - notes.justinlucedev.com 